work_related_credentials = [
    "job_email",
    "access_card",
    "vpn",
    "otp",
    "ssh_keys",
    "api_key",
    "Personal Information Collection",
    "Purpose of Data Collection",
    "Data Usage and Sharing",
    "Cookie Usage",
    "Data Retention",
    "User Control",
    "Security Measures",
    "Legal Basis for Data Processing",
    "Third-Party Links",
    "Children's Privacy",
    "Data Transfer",
]
